spec = {
    'get_me': {'method': 'get',
               'path': '/getMe'},
    'get_updates': {'method': 'post',
                    'path': '/getUpdates'},
    'get_file': {'method': 'post',
                 'path': '/getFile'},
    'download_file': {'method': 'get',
                      'path': '/{file_path}',
                      'stream_response': True,
                      'path_tokens': {'prefix': 'file/'}},
    'get_user_profile_photos': {'method': 'post',
                                'path': '/getUserProfilePhotos'},
    'set_webhook': {'method': 'post',
                    'path': '/setWebhook'},
    'send_message': {'method': 'post',
                     'path': '/sendMessage'},
    'send_location': {'method': 'post',
                      'path': '/sendLocation'},
    'forward_message': {'method': 'post',
                        'path': '/forwardMessage'},
    'send_photo': {'method': 'post',
                   'path': '/sendPhoto'},
    'send_audio': {'method': 'post',
                   'path': '/sendAudio'},
    'send_document': {'method': 'post',
                      'path': '/sendDocument'},
    'send_sticker': {'method': 'post',
                     'path': '/sendSticker'},
    'send_video': {'method': 'post',
                   'path': '/sendVideo'},
    'send_voice': {'method': 'post',
                   'path': '/sendVoice'},
    'send_venue': {'method': 'post',
                   'path': '/sendVenue'},
    'send_contact': {'method': 'post',
                     'path': '/sendContact'},
    'send_chat_action': {'method': 'post',
                         'path': '/sendChatAction'},
    'answer_inline_query': {'method': 'post',
                            'path': '/answerInlineQuery'},
    'answer_callback_query': {'method': 'post',
                              'path': '/answerCallbackQuery'},
    'edit_message_text': {'method': 'post',
                          'path': '/editMessageText'},
    'edit_message_caption': {'method': 'post',
                             'path': '/editMessageCaption'},
    'edit_message_reply_markup': {'method': 'post',
                                  'path': '/editMessageReplyMarkup'},
    'kick_chat_member': {'method': 'post',
                         'path': '/kickChatMember'},
    'leave_chat': {'method': 'post',
                   'path': '/leaveChat'},
    'unban_chat_member': {'method': 'post',
                          'path': '/unbanChatMember'},
    'get_chat': {'method': 'post',
                 'path': '/getChat'},
    'get_chat_administrators': {'method': 'post',
                                'path': '/getChatAdministrators'},
    'get_chat_members_count': {'method': 'post',
                               'path': '/getChatMembersCount'},
    'get_chat_member': {'method': 'post',
                        'path': '/getChatMember'}
}
